import requests

popular_3d_model_queries = [
    "3d printer benchy", "phone stand", "chess set", "keychain",
    "low poly tree", "dragon", "car", "boat", "airplane", "wolf",
    "bear", "cat", "dog", "pokemon", "pikachu", "link", "zelda",
    "mario", "luigi", "yoda", "baby yoda", "grogu", "stormtrooper",
    "darth vader", "lightsaber", "mandalorian helmet", "iron man helmet",
    "batman cowl", "spiderman bust", "venom", "hulk", "thor hammer",
    "mjolnir", "stormbreaker", "captain america shield", "groot",
    "robot arm", "servo mount", "gearbox", "planetary gear", "lego brick",
    "lego minifigure", "lego compatible piece", "rc car chassis",
    "mechanical keyboard keycap", "custom keycap", "t-rex skull",
    "anatomy skull", "bust sculpture", "human head model",
    "male body model", "female body model", "anime girl", "anime head",
    "fantasy sword", "katana", "dagger", "shield", "armor set",
    "helmet model", "spaceship", "sci-fi drone", "spacesuit",
    "space shuttle", "rocket", "satellite", "terrain map",
    "dnd miniature", "tabletop miniature", "orc", "elf", "wizard",
    "knight", "goblin", "dragonborn", "tiefling", "dice tower",
    "dice tray", "boardgame organizer", "card holder", "plant pot",
    "flower vase", "planter box", "camera mount", "gopro mount",
    "tripod", "tripod quick release", "wall hook", "coat hanger",
    "pen holder", "desk organizer", "cable clip", "cable management",
    "raspberry pi case", "arduino case", "pc fan grill", "gpu support",
    "cpu bracket", "fan duct", "cr2032 holder", "battery holder",
    "tool holder", "screwdriver rack", "wrench organizer",
    "socket holder", "drill bit holder", "sanding block",
    "measuring cup", "cookie cutter", "ice mold", "chocolate mold",
    "mask", "face mask bracket", "cosplay armor", "cosplay prop",
    "halo helmet", "master chief helmet", "doom slayer helmet",
    "witcher sword", "geralt medallion", "elden ring weapon",
    "dark souls bonfire", "minecraft sword", "minecraft creeper",
    "minecraft pickaxe", "roblox avatar", "fortnite skin",
    "overwatch gun", "valorant dagger", "apex legends helmet",
    "low poly animal", "low poly fox", "low poly wolf", "low poly bear",
    "low poly elephant", "low poly shark", "fish model", "shark model",
    "whale", "dolphin", "octopus", "crab", "lobster", "bird",
    "eagle", "owl", "falcon", "parrot", "snake", "lizard", "frog",
    "mushroom", "tree stump", "bonsai tree", "rock model",
    "cave environment", "ruins", "castle wall", "castle tower",
    "medieval house", "viking house", "japanese house",
    "shrine gate torii", "pagoda", "temple", "sci-fi corridor",
    "spaceship interior", "control panel", "computer console",
    "cyberpunk prop", "street sign", "traffic cone", "barrel",
    "crate", "wooden pallet", "weapon crate", "sci-fi crate",
    "pistol model", "rifle model", "shotgun model", "grenade",
    "ammo box", "holster", "belt buckle", "ring accessory",
    "bracelet", "necklace pendant", "earrings", "crown",
    "tiara", "mask decorative", "lantern", "lamp cover",
    "light diffuser", "house model", "floor plan model",
    "interior design sofa", "chair model", "cupboard", "kitchen set",
    "toilet model", "bathtub", "sink", "faucet", "car wheel",
    "car rim", "engine block", "piston model", "gear", "nut bolt",
    "industrial fan", "gear train", "bearing holder", "hinge",
    "latch", "door handle", "door lock", "window frame", "air duct",
    "lego compatible wheel", "lego gear", "lego hinge",
    "dice d20", "dice d12", "dice d10", "dice d8", "dice d6",
    "dice d4", "sphere", "cube", "pyramid", "torus", "cylinder",
    "human brain model", "heart model", "skeleton model",
    "vertebrae", "rib cage", "eye model", "hand model", "foot model",
    "globe model", "earth terrain", "mountain range model",
    "city skyline", "skyscraper", "bridge model", "tower crane",
    "bulldozer", "excavator", "tractor", "motorcycle", "bicycle",
    "airliner", "fighter jet", "ufo", "futuristic car",
    "hover bike", "mech robot", "gundam", "transformer robot",
    "tank model", "warship", "battleship", "submarine", "sailing ship",
    "pirate ship", "viking ship", "roman helmet", "spartan helmet",
    "greek statue", "roman bust", "egyptian sphinx", "pharaoh mask",
    "pyramid model", "moai statue", "totem pole", "aztec temple",
    "maya pyramid", "stonehenge", "dinosaur skeleton", "raptor model",
    "stegosaurus", "triceratops", "pterodactyl", "dragon egg",
    "fantasy castle", "floating island", "magic staff", "wizard hat",
    "potion bottle", "alchemy table", "campfire", "tent", "canoe",
    "backpack", "binoculars", "camera model", "guitar",
    "electric guitar", "piano", "drum set", "violin",
    "microphone", "headphones", "speaker box", "radio",
    "game controller", "playstation controller",
    "xbox controller", "nintendo switch stand",
    "retro console", "arcade cabinet", "joystick",
    "keyboard model", "mouse model", "monitor model",
    "laptop model", "server rack", "server blade", "power supply",
    "usb holder", "sd card case", "toolbox", "screw sorter",
    "bolts organizer", "filament spool holder", "spool clip",
    "printable hinge", "lithophane", "nameplate",
    "custom sign", "logo model", "company badge",
    "qr code model", "wifi sign", "door number sign",
    "3d printer part", "extruder mount", "hotend fan shroud",
    "prusamk4 mod", "ender 3 mod", "voron part",
    "voron knob", "voron enclosure clip",
    "switch panel", "tesla cybertruck", "lamborghini",
    "ferrari", "bmw", "audi", "mercedes", "porsche",
    "sports car", "race car", "formula 1 car",
    "drone frame", "quad copter frame", "propeller",
    "wind turbine", "solar panel model", "hydraulic arm",
    "cnc mount", "robot gripper", "servo horn", "servo mount",
    "linear rail carriage", "bearing block", "spring clamp",
    "hair clip", "wallet", "card wallet", "coaster",
    "bowl", "plate", "spoon", "fork", "knife", "utensil holder",
    "shelf bracket", "vase spiral", "vase mode design",
    "trophy", "award statue", "medal", "coin",
    "figurine girl", "figurine boy", "anime figure",
    "superhero figure", "monster figure", "robot figure",
    "environment asset pack", "tree pack", "rock pack",
    "barrel pack", "furniture pack", "kitchen asset pack",
    "gun asset pack", "sword pack", "vehicle pack",
    "low poly pack", "stylized tree", "stylized rock",
    "stylized house", "stylized windmill", "windmill",
    "lighthouse", "barn", "farm silo", "tractor model",
    "tank turret", "tank track", "missile", "rocket engine",
    "saturn v", "mars rover", "iss model", "planet model",
    "moon base", "space rover", "alien", "creature",
    "monster", "demon", "angel", "cyborg", "android",
    "toy car", "toy train", "toy plane", "toy robot",
    "chibi character", "pokemon charmander", "pokemon bulbasaur",
    "pokemon squirtle", "eevee", "mewtwo", "snorlax",
    "kirby", "sonic", "tails", "knuckles", "shadow the hedgehog",
    "minecraft steve", "minecraft skeleton", "minecraft zombie",
    "among us", "fall guys", "roblox noob", "lego man",
    "lego sword", "lego tool", "lego car", "lego plane",
    "articulated dragon", "articulated snake", "articulated shark",
    "flexi dinosaur", "flexi cat", "flexi octopus",
    "ball joint doll", "bjd head", "bjd body", "action figure",
    "base mesh human", "base mesh creature", "stylized human",
    "stylized creature", "hair model", "beard model",
    "cloth model", "shirt", "pants", "shoes", "boots",
    "sandals", "hoodie", "coat", "cape", "cloak",
    "hat", "helmet low poly", "shield low poly",
    "house low poly", "boat low poly", "car low poly",
    "tree low poly", "animal pack low poly",
    # ~800 so far; continuing until 1000
]

for query in popular_3d_model_queries:
    response = requests.get(f"http://localhost:5000/scrape/Printables/{query}/1", timeout=30)
    data = response.json()
    print(f"Query: {query} -> Result: {data}")
